{"name": "Finalize call API -- @1.1 ", "status": "failed", "statusDetails": {"message": "AssertionError: Expected <6843> to be equal to <0>, but was not.\n", "trace": "  File \"C:\\Users\\Noman Sial\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Noman Sial\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\stepimpl.py\", line 51, in step_impl\n    assert_that(context.generated_response_code).is_equal_to(\"0\")\n  File \"C:\\Users\\Noman Sial\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\assertpy\\base.py\", line 126, in is_equal_to\n    self.error('Expected <%s> to be equal to <%s>, but was not.' % (self.val, other))\n  File \"C:\\Users\\Noman Sial\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\assertpy\\assertpy.py\", line 433, in error\n    raise AssertionError(out)\n"}, "steps": [{"name": "Given API headers are provided", "status": "passed", "start": 1640106365217, "stop": 1640106365218}, {"name": "When so when Demo Merchant and en", "status": "passed", "start": 1640106365218, "stop": 1640106366018}, {"name": "Then Status code is returned", "status": "failed", "statusDetails": {"message": "AssertionError: Expected <6843> to be equal to <0>, but was not.\n", "trace": "  File \"C:\\Users\\Noman Sial\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Noman Sial\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\stepimpl.py\", line 51, in step_impl\n    assert_that(context.generated_response_code).is_equal_to(\"0\")\n  File \"C:\\Users\\Noman Sial\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\assertpy\\base.py\", line 126, in is_equal_to\n    self.error('Expected <%s> to be equal to <%s>, but was not.' % (self.val, other))\n  File \"C:\\Users\\Noman Sial\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\assertpy\\assertpy.py\", line 433, in error\n    raise AssertionError(out)\n"}, "start": 1640106366018, "stop": 1640106366020}], "parameters": [{"name": "customerName", "value": "Demo Merchant"}, {"name": "lang", "value": "en"}], "start": 1640106365215, "stop": 1640106366021, "uuid": "f2260930-45ec-4b2d-bdb4-2b40e7bfa7f3", "historyId": "a4da13ea557dfa24ef373ccde4cfe2ae", "fullName": "Manual Merchant Registration: Finalize call API", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "Dunedin"}, {"name": "feature", "value": "Manual Merchant Registration"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}